# Generated by Django 4.2 on 2023-07-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_bookcomment_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookSearch",
        ),
    ]
