# Generated by Django 4.2 on 2023-07-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookSearching",
        ),
    ]
