# Generated by Django 4.2 on 2023-06-28 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(default="", max_length=200, unique=True)),
                ("password", models.CharField(default="", max_length=128)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=10)),
                (
                    "img_src",
                    models.CharField(
                        default="https://w7.pngwing.com/pngs/441/722/png-transparent-pikachu-thumbnail.png",
                        max_length=100,
                    ),
                ),
                ("nickname", models.CharField(max_length=16)),
                ("pw_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("birth", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=1),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="user_favor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("favor1", models.CharField(max_length=30)),
                ("favor2", models.CharField(max_length=30)),
                ("favor3", models.CharField(max_length=30)),
                ("favor4", models.CharField(max_length=30)),
            ],
        ),
    ]
